### PR TITLE
bump to micromatch@2

### PR DESCRIPTION
**Pull request by tunnckoCore**
like that? lol

### CODE REVIEW

**Comment by jonschlinkert** [comment]
thanks! exactly the kind of pr I like :)

**Comment by jonschlinkert** [comment]
easy to review, easy to merge, easy to do quickly :) thanks

**Comment by tunnckoCore** [comment]
lol, no prob. :sparkling_heart:

**Comment by tunnckoCore** [comment]
thanks, https://github.com/tunnckoCore/load-deps ;]

**Comment by jonschlinkert** [comment]
nice work on load-deps, looks great

**Comment by tunnckoCore** [comment]
@jonschlinkert yea, thanks. :star2:

**Pull request merged**
