### PR TITLE
bump deps

### PR DESCRIPTION
**Pull request by tunnckoCore**
just because i'm playing with some globs here and still see more value on this instead using micromatch.

i'll install the fork for the game, if you're busy currently to publish

### CODE REVIEW

**Comment by jonschlinkert** [comment]
published and released as 0.4.1. thanks!

**Comment by tunnckoCore** [comment]
Great!

**Comment by jonschlinkert** [comment]
@tunnckoCore recently you asked me about something with unit tests... I can't remember what it was but I think you suggested a better way of testing something with `assert`. do you remember what that was?

**Comment by tunnckoCore** [comment]
Haha, maybe you mean that testing for that if something throws? I use assert.throws you said that you like try/catch blocks. I do it like so

``` js
var  fn = require('my-fn')
fixture () {
  fn(123)
}
assert.throws(fixture, TypeError)
assert.throws(fixture, /expect a string/)
```

I can't remember other. This looks cleaner and better to me instead of `try/catch` blocks

**Comment by jonschlinkert** [comment]
Oh yeah, maybe that's what it was, `assert.throws`. I don't know why I keep forgetting about that method! thx

**Pull request merged**
